name: Generate reasonably sized images
on:
  push:
    branches:
      - main
    paths:
      - "images/**"
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: Disable workflow commands
        run: |
	  npm install -g recursive-resize
          recres -i images/ -o reasonable-images/ -w 2000
      - name: Commit & Push changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
          BRANCH_NAME: 'main'
