name: Generate thumbnails
on:
  push:
    branches:
      - main
    paths:
      - "images/**"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: custom-thumbnail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: custom-thumbnail
        uses: nathan-contino/custom-thumbnail@master
        with:
          github_token: ${{ secrets.GH_SECRET}}
          inplace: "disable" # 'enable' / "disable" [ write thumbnails at their origin path (replace) ], if disabled writes under '.thumbnails' directory 
          base_height_width: "1000" # (px) max limit of height/width
          keep_dir_structure: "enable" # 'enable'/'disable' keep the input images directory structure while writing to .thumbnails directory
          overwrite_existing_thumbnails: "disable"
      - name: Commit & Push changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
          BRANCH_NAME: 'main'
